
I0601 17:12:32.829307 139725702133504 _logging.py:76] Websocket connected
Environment Ready!!
CustomEnv Environment initialized
For debug - env created
For debug - ds created
/home/howard/anaconda3/envs/rlpd/lib/python3.9/site-packages/gym/spaces/box.py:73: UserWarning: [33mWARN: Box bound precision lowered by casting to float32
  logger.warn(
I0601 17:12:35.312951 139727159305792 xla_bridge.py:455] Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: Host CUDA Interpreter
I0601 17:12:35.335850 139727159305792 xla_bridge.py:455] Unable to initialize backend 'tpu': module 'jaxlib.xla_extension' has no attribute 'get_tpu_client'
I0601 17:12:35.337408 139727159305792 xla_bridge.py:455] Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
For debug - agent created
For debug - replay_buffer created





  1%|â–‰                                                                                                                                   | 145/20000 [00:15<35:11,  9.41it/s]
Traceback (most recent call last):
  File "/home/howard/RLproject/train_finetuning.py", line 275, in <module>
    app.run(main)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/howard/anaconda3/envs/rlpd/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 643, in write
    cb(data)
  File "/home/howard/anaconda3/envs/rlpd/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2088, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/howard/anaconda3/envs/rlpd/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 345, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/howard/anaconda3/envs/rlpd/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1428, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/howard/anaconda3/envs/rlpd/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 657, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/howard/anaconda3/envs/rlpd/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 79, in _publish_output_raw
    self._publish(rec)
  File "/home/howard/anaconda3/envs/rlpd/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/howard/anaconda3/envs/rlpd/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
  File "/home/howard/anaconda3/envs/rlpd/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/howard/anaconda3/envs/rlpd/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/howard/anaconda3/envs/rlpd/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
KeyboardInterrupt
Original exception was:
Traceback (most recent call last):
  File "/home/howard/RLproject/train_finetuning.py", line 275, in <module>
    app.run(main)
  File "/home/howard/anaconda3/envs/rlpd/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/howard/anaconda3/envs/rlpd/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/howard/RLproject/train_finetuning.py", line 153, in main
    agent, update_info = agent.update(batch, FLAGS.utd_ratio)
  File "/home/howard/anaconda3/envs/rlpd/lib/python3.9/site-packages/flax/core/frozen_dict.py", line 162, in tree_unflatten
    @classmethod
KeyboardInterrupt
Exception ignored in: <module 'threading' from '/home/howard/anaconda3/envs/rlpd/lib/python3.9/threading.py'>
Traceback (most recent call last):
  File "/home/howard/anaconda3/envs/rlpd/lib/python3.9/threading.py", line 1477, in _shutdown
    lock.acquire()
KeyboardInterrupt: